# Generated by Django 2.1.3 on 2018-11-27 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181126_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='freelancer',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
