# Generated by Django 2.1.4 on 2019-01-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20181217_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/users/no-avatar.jpg', upload_to='images/users'),
        ),
    ]
